version: 2
updates:
  # For Python dependencies
  - package-ecosystem: "pip"
    directory: "/" # Directory where your requirements.txt is located
    schedule:
      interval: "weekly"

  # For Node.js dependencies (if applicable)
  - package-ecosystem: "npm"
    directory: "/" # Directory where your package.json is located
    schedule:
      interval: "weekly"

  # For Docker (if using Docker)
  - package-ecosystem: "docker"
    directory: "/" # Directory where your Dockerfile is located
    schedule:
      interval: "weekly
